services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - DMS-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=DMSDB;Username=dmsadmin;Password=dmsadmin"
    depends_on:
      - postgres
  
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "dmsadmin"
      POSTGRES_PASSWORD: "dmsadmin"
      POSTGRES_DB: "DMSDB"
      DB_DATABASE_NAME: "DMSDB"
      DB_USERNAME: "dmsadmin"
      DB_PASSWORD: "dmsadmin"
      DB_DATA_LOCATION: "/var/lib/postgresql/data"
      UPLOAD_LOCATION: "/var/lib/postgresql/data"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./psqldatabase:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - DMS-network

networks:
  DMS-network:
    driver: bridge
