services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    # networks:
    #   - DMS-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=DMSdb;Username=myuser;Password=mypassword"
    # depends_on:
    #   - postgres

  # frontend:
  #   build:
  #     context: ./DMS-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - DMS-network
  #   depends_on:
  #     - api

#   postgres:
#     image: "postgres:13"
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: DMSdb
#     ports:
#       - "5432:5432"
#     networks:
#       - DMS-network

# networks:
#   DMS-network:
#     driver: bridge
